version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: roi-backend:latest
    container_name: roi-backend
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: roi-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
